// Iconic K-pop canon: the genuinely famous title tracks (gen 1-5) that belong
// in the 'iconic' tier regardless of current Deezer streaming rank, so classics
// (Gee, Sorry Sorry, Fantastic Baby, Gangnam Style...) tier correctly.
//
// Matched against the built set by NORMALIZED (artist, title) - see populate-
// curated.mjs normKey(). Artist names mirror kpop-artists-catalog.mjs. Entries
// for artists not in the catalog are simply inert.

export const CANON = [
  // ===== 1st / 2nd gen groups =====
  { artist: 'H.O.T.', title: 'Candy' },
  { artist: 'Sechs Kies', title: 'Couple' },
  { artist: 'S.E.S.', title: "I'm Your Girl" },
  { artist: 'Fin.K.L', title: 'To My Boyfriend' },
  { artist: 'g.o.d', title: 'Lies' },
  { artist: 'g.o.d', title: 'One Candle' },
  { artist: 'Shinhwa', title: 'Brand New' },
  { artist: 'Shinhwa', title: 'Perfect Man' },
  { artist: 'TVXQ!', title: 'Mirotic' },
  { artist: 'TVXQ!', title: 'Rising Sun' },
  { artist: 'TVXQ!', title: 'Hug' },
  { artist: 'TVXQ!', title: 'Catch Me' },
  { artist: 'Super Junior', title: 'Sorry Sorry' },
  { artist: 'Super Junior', title: 'Mr. Simple' },
  { artist: 'Super Junior', title: 'Bonamana' },
  { artist: 'Super Junior', title: 'Sexy, Free & Single' },
  { artist: 'Super Junior', title: 'Devil' },
  { artist: 'BIGBANG', title: 'Lies' },
  { artist: 'BIGBANG', title: 'Haru Haru' },
  { artist: 'BIGBANG', title: 'Fantastic Baby' },
  { artist: 'BIGBANG', title: 'Bang Bang Bang' },
  { artist: 'BIGBANG', title: 'Bae Bae' },
  { artist: 'BIGBANG', title: 'Loser' },
  { artist: 'BIGBANG', title: 'Last Dance' },
  { artist: 'BIGBANG', title: 'Tonight' },
  { artist: 'BIGBANG', title: 'Sober' },
  { artist: '2NE1', title: 'I Am the Best' },
  { artist: '2NE1', title: 'Fire' },
  { artist: '2NE1', title: 'Come Back Home' },
  { artist: '2NE1', title: 'Ugly' },
  { artist: '2NE1', title: 'Lonely' },
  { artist: '2NE1', title: "Can't Nobody" },
  { artist: '2NE1', title: 'Falling in Love' },
  { artist: 'Wonder Girls', title: 'Tell Me' },
  { artist: 'Wonder Girls', title: 'Nobody' },
  { artist: 'Wonder Girls', title: 'So Hot' },
  { artist: 'Wonder Girls', title: 'Be My Baby' },
  { artist: "Girls' Generation", title: 'Gee' },
  { artist: "Girls' Generation", title: 'Genie' },
  { artist: "Girls' Generation", title: 'The Boys' },
  { artist: "Girls' Generation", title: 'I Got a Boy' },
  { artist: "Girls' Generation", title: 'Mr. Taxi' },
  { artist: "Girls' Generation", title: 'Run Devil Run' },
  { artist: "Girls' Generation", title: 'Oh!' },
  { artist: "Girls' Generation", title: 'Lion Heart' },
  { artist: "Girls' Generation", title: 'Into the New World' },
  { artist: "Girls' Generation", title: 'Party' },
  { artist: "Girls' Generation", title: 'Forever 1' },
  { artist: 'KARA', title: 'Mister' },
  { artist: 'KARA', title: 'Pretty Girl' },
  { artist: 'KARA', title: 'Step' },
  { artist: 'KARA', title: 'Mamma Mia' },
  { artist: '4Minute', title: 'Crazy' },
  { artist: '4Minute', title: 'Hot Issue' },
  { artist: '4Minute', title: 'Mirror Mirror' },
  { artist: 'T-ara', title: 'Roly-Poly' },
  { artist: 'T-ara', title: 'Bo Peep Bo Peep' },
  { artist: 'T-ara', title: 'Lovey-Dovey' },
  { artist: 'T-ara', title: 'Number 9' },
  { artist: 'T-ara', title: 'Sugar Free' },
  { artist: 'f(x)', title: 'Nu ABO' },
  { artist: 'f(x)', title: 'Electric Shock' },
  { artist: 'f(x)', title: 'Rum Pum Pum Pum' },
  { artist: 'f(x)', title: '4 Walls' },
  { artist: 'f(x)', title: 'Hot Summer' },
  { artist: 'SHINee', title: 'Replay' },
  { artist: 'SHINee', title: 'Ring Ding Dong' },
  { artist: 'SHINee', title: 'Lucifer' },
  { artist: 'SHINee', title: 'Sherlock' },
  { artist: 'SHINee', title: 'View' },
  { artist: 'SHINee', title: 'Married to the Music' },
  { artist: 'SHINee', title: '1 of 1' },
  { artist: 'SHINee', title: "Don't Call Me" },
  { artist: '2PM', title: 'Again & Again' },
  { artist: '2PM', title: 'Heartbeat' },
  { artist: '2PM', title: 'Hands Up' },
  { artist: '2PM', title: 'A.D.T.O.Y.' },
  { artist: '2PM', title: 'My House' },
  { artist: 'Highlight', title: 'Fiction' },
  { artist: 'BEAST', title: 'Fiction' },
  { artist: 'BEAST', title: 'Shock' },
  { artist: 'Sistar', title: 'Alone' },
  { artist: 'Sistar', title: 'Touch My Body' },
  { artist: 'Sistar', title: 'Shake It' },
  { artist: 'Sistar', title: 'Loving U' },
  { artist: 'Secret', title: 'Magic' },
  { artist: 'Secret', title: 'Shy Boy' },
  { artist: 'miss A', title: 'Bad Girl Good Girl' },
  { artist: 'miss A', title: 'Hush' },
  { artist: 'Brown Eyed Girls', title: 'Abracadabra' },
  { artist: 'After School', title: 'Bang!' },
  { artist: 'Apink', title: 'NoNoNo' },
  { artist: 'Apink', title: "I'm So Sick" },
  { artist: 'Apink', title: 'Mr. Chu' },

  // ===== 3rd gen girl groups =====
  { artist: 'TWICE', title: 'Like OOH-AHH' },
  { artist: 'TWICE', title: 'Cheer Up' },
  { artist: 'TWICE', title: 'TT' },
  { artist: 'TWICE', title: 'Knock Knock' },
  { artist: 'TWICE', title: 'Signal' },
  { artist: 'TWICE', title: 'Likey' },
  { artist: 'TWICE', title: 'Heart Shaker' },
  { artist: 'TWICE', title: 'What is Love?' },
  { artist: 'TWICE', title: 'Dance the Night Away' },
  { artist: 'TWICE', title: 'Yes or Yes' },
  { artist: 'TWICE', title: 'Fancy' },
  { artist: 'TWICE', title: 'Feel Special' },
  { artist: 'TWICE', title: 'More & More' },
  { artist: 'TWICE', title: "I Can't Stop Me" },
  { artist: 'TWICE', title: 'Alcohol-Free' },
  { artist: 'TWICE', title: 'The Feels' },
  { artist: 'TWICE', title: 'Talk that Talk' },
  { artist: 'TWICE', title: 'Set Me Free' },
  { artist: 'BLACKPINK', title: 'BOOMBAYAH' },
  { artist: 'BLACKPINK', title: 'Whistle' },
  { artist: 'BLACKPINK', title: 'Playing with Fire' },
  { artist: 'BLACKPINK', title: "As If It's Your Last" },
  { artist: 'BLACKPINK', title: 'DDU-DU DDU-DU' },
  { artist: 'BLACKPINK', title: 'Kill This Love' },
  { artist: 'BLACKPINK', title: 'How You Like That' },
  { artist: 'BLACKPINK', title: 'Ice Cream' },
  { artist: 'BLACKPINK', title: 'Lovesick Girls' },
  { artist: 'BLACKPINK', title: 'Pink Venom' },
  { artist: 'BLACKPINK', title: 'Shut Down' },
  { artist: 'BLACKPINK', title: 'Pretty Savage' },
  { artist: 'BLACKPINK', title: 'Forever Young' },
  { artist: 'Red Velvet', title: 'Happiness' },
  { artist: 'Red Velvet', title: 'Ice Cream Cake' },
  { artist: 'Red Velvet', title: 'Dumb Dumb' },
  { artist: 'Red Velvet', title: 'Russian Roulette' },
  { artist: 'Red Velvet', title: 'Rookie' },
  { artist: 'Red Velvet', title: 'Red Flavor' },
  { artist: 'Red Velvet', title: 'Peek-A-Boo' },
  { artist: 'Red Velvet', title: 'Bad Boy' },
  { artist: 'Red Velvet', title: 'Power Up' },
  { artist: 'Red Velvet', title: 'Psycho' },
  { artist: 'Red Velvet', title: 'Queendom' },
  { artist: 'Red Velvet', title: 'Feel My Rhythm' },
  { artist: 'MAMAMOO', title: 'Decalcomanie' },
  { artist: 'MAMAMOO', title: 'Starry Night' },
  { artist: 'MAMAMOO', title: 'Egotistic' },
  { artist: 'MAMAMOO', title: 'Hip' },
  { artist: 'MAMAMOO', title: 'Gogobebe' },
  { artist: 'MAMAMOO', title: "You're the Best" },
  { artist: 'GFRIEND', title: 'Glass Bead' },
  { artist: 'GFRIEND', title: 'Me Gustas Tu' },
  { artist: 'GFRIEND', title: 'Rough' },
  { artist: 'GFRIEND', title: 'Navillera' },
  { artist: 'GFRIEND', title: 'Time for the Moon Night' },
  { artist: 'GFRIEND', title: 'Mago' },
  { artist: 'OH MY GIRL', title: 'Closer' },
  { artist: 'OH MY GIRL', title: 'Secret Garden' },
  { artist: 'OH MY GIRL', title: 'Nonstop' },
  { artist: 'OH MY GIRL', title: 'Dolphin' },
  { artist: 'OH MY GIRL', title: 'Bungee' },
  { artist: 'LOONA', title: 'Hi High' },
  { artist: 'LOONA', title: 'So What' },
  { artist: 'LOONA', title: 'PTT (Paint The Town)' },
  { artist: 'EVERGLOW', title: 'Bon Bon Chocolat' },
  { artist: 'EVERGLOW', title: 'Dun Dun' },
  { artist: 'EVERGLOW', title: 'La Di Da' },
  { artist: 'EXID', title: 'Up & Down' },
  { artist: 'MOMOLAND', title: 'Bboom Bboom' },

  // ===== 3rd gen boy groups =====
  { artist: 'BTS', title: 'No More Dream' },
  { artist: 'BTS', title: 'Boy in Luv' },
  { artist: 'BTS', title: 'I Need U' },
  { artist: 'BTS', title: 'Dope' },
  { artist: 'BTS', title: 'Run' },
  { artist: 'BTS', title: 'Fire' },
  { artist: 'BTS', title: 'Blood Sweat & Tears' },
  { artist: 'BTS', title: 'Spring Day' },
  { artist: 'BTS', title: 'DNA' },
  { artist: 'BTS', title: 'Mic Drop' },
  { artist: 'BTS', title: 'Fake Love' },
  { artist: 'BTS', title: 'Idol' },
  { artist: 'BTS', title: 'Boy With Luv' },
  { artist: 'BTS', title: 'Dynamite' },
  { artist: 'BTS', title: 'Butter' },
  { artist: 'BTS', title: 'Permission to Dance' },
  { artist: 'BTS', title: 'Life Goes On' },
  { artist: 'BTS', title: 'ON' },
  { artist: 'BTS', title: 'Black Swan' },
  { artist: 'BTS', title: 'Not Today' },
  { artist: 'BTS', title: 'Save Me' },
  { artist: 'EXO', title: 'MAMA' },
  { artist: 'EXO', title: 'Wolf' },
  { artist: 'EXO', title: 'Growl' },
  { artist: 'EXO', title: 'Overdose' },
  { artist: 'EXO', title: 'Call Me Baby' },
  { artist: 'EXO', title: 'Love Me Right' },
  { artist: 'EXO', title: 'Monster' },
  { artist: 'EXO', title: 'Lotto' },
  { artist: 'EXO', title: 'Ko Ko Bop' },
  { artist: 'EXO', title: 'Power' },
  { artist: 'EXO', title: 'Tempo' },
  { artist: 'EXO', title: 'Love Shot' },
  { artist: 'EXO', title: 'Obsession' },
  { artist: 'SEVENTEEN', title: 'Adore U' },
  { artist: 'SEVENTEEN', title: 'Mansae' },
  { artist: 'SEVENTEEN', title: 'Pretty U' },
  { artist: 'SEVENTEEN', title: 'Very Nice' },
  { artist: 'SEVENTEEN', title: 'Boom Boom' },
  { artist: 'SEVENTEEN', title: "Don't Wanna Cry" },
  { artist: 'SEVENTEEN', title: 'Clap' },
  { artist: 'SEVENTEEN', title: 'Home' },
  { artist: 'SEVENTEEN', title: 'Fear' },
  { artist: 'SEVENTEEN', title: 'Left & Right' },
  { artist: 'SEVENTEEN', title: 'Ready to Love' },
  { artist: 'SEVENTEEN', title: 'Rock with You' },
  { artist: 'SEVENTEEN', title: 'HOT' },
  { artist: 'SEVENTEEN', title: 'Super' },
  { artist: 'SEVENTEEN', title: 'God of Music' },
  { artist: 'SEVENTEEN', title: 'MAESTRO' },
  { artist: 'GOT7', title: 'A' },
  { artist: 'GOT7', title: 'Just Right' },
  { artist: 'GOT7', title: 'If You Do' },
  { artist: 'GOT7', title: 'Hard Carry' },
  { artist: 'GOT7', title: 'Never Ever' },
  { artist: 'GOT7', title: 'Lullaby' },
  { artist: 'GOT7', title: 'You Calling My Name' },
  { artist: 'MONSTA X', title: 'Trespass' },
  { artist: 'MONSTA X', title: 'Beautiful' },
  { artist: 'MONSTA X', title: 'Dramarama' },
  { artist: 'MONSTA X', title: 'Shoot Out' },
  { artist: 'MONSTA X', title: 'Alligator' },
  { artist: 'MONSTA X', title: 'Follow' },
  { artist: 'NCT 127', title: 'Firetruck' },
  { artist: 'NCT 127', title: 'Cherry Bomb' },
  { artist: 'NCT 127', title: 'Regular' },
  { artist: 'NCT 127', title: 'Simon Says' },
  { artist: 'NCT 127', title: 'Superhuman' },
  { artist: 'NCT 127', title: 'Kick It' },
  { artist: 'NCT 127', title: 'Punch' },
  { artist: 'NCT 127', title: 'Sticker' },
  { artist: 'NCT 127', title: '2 Baddies' },
  { artist: 'NCT DREAM', title: 'Chewing Gum' },
  { artist: 'NCT DREAM', title: 'We Young' },
  { artist: 'NCT DREAM', title: 'Go' },
  { artist: 'NCT DREAM', title: 'Boom' },
  { artist: 'NCT DREAM', title: "Ridin'" },
  { artist: 'NCT DREAM', title: 'Hot Sauce' },
  { artist: 'NCT DREAM', title: 'Glitch Mode' },
  { artist: 'NCT DREAM', title: 'Candy' },
  { artist: 'NCT DREAM', title: 'ISTJ' },
  { artist: 'WayV', title: 'Love Talk' },
  { artist: 'iKON', title: 'Love Scenario' },
  { artist: 'iKON', title: 'Killing Me' },
  { artist: 'iKON', title: 'Rhythm Ta' },
  { artist: 'iKON', title: 'Dumb & Dumber' },
  { artist: 'iKON', title: 'My Type' },
  { artist: 'WINNER', title: 'Really Really' },
  { artist: 'WINNER', title: 'Empty' },
  { artist: 'WINNER', title: 'Love Me Love Me' },
  { artist: 'WINNER', title: 'Everyday' },
  { artist: 'ASTRO', title: 'Crazy Sexy Cool' },
  { artist: 'ASTRO', title: 'All Night' },
  { artist: 'PENTAGON', title: 'Shine' },
  { artist: 'PENTAGON', title: 'Naughty Boy' },
  { artist: 'THE BOYZ', title: 'Bloom Bloom' },
  { artist: 'THE BOYZ', title: 'Reveal' },
  { artist: 'THE BOYZ', title: 'The Stealer' },
  { artist: 'THE BOYZ', title: 'Thrill Ride' },
  { artist: 'Wanna One', title: 'Energetic' },
  { artist: 'Wanna One', title: 'Beautiful' },
  { artist: 'Wanna One', title: 'Boomerang' },

  // ===== 4th / 5th gen girl groups =====
  { artist: 'aespa', title: 'Black Mamba' },
  { artist: 'aespa', title: 'Next Level' },
  { artist: 'aespa', title: 'Savage' },
  { artist: 'aespa', title: 'Girls' },
  { artist: 'aespa', title: 'Spicy' },
  { artist: 'aespa', title: 'Drama' },
  { artist: 'aespa', title: 'Supernova' },
  { artist: 'aespa', title: 'Armageddon' },
  { artist: 'aespa', title: 'Whiplash' },
  { artist: 'ITZY', title: 'DALLA DALLA' },
  { artist: 'ITZY', title: 'ICY' },
  { artist: 'ITZY', title: 'WANNABE' },
  { artist: 'ITZY', title: 'Not Shy' },
  { artist: 'ITZY', title: 'In the Morning' },
  { artist: 'ITZY', title: 'LOCO' },
  { artist: 'ITZY', title: 'SNEAKERS' },
  { artist: 'ITZY', title: 'Cake' },
  { artist: 'ITZY', title: 'Born to Be' },
  { artist: '(G)I-DLE', title: 'LATATA' },
  { artist: '(G)I-DLE', title: 'Hann' },
  { artist: '(G)I-DLE', title: 'Senorita' },
  { artist: '(G)I-DLE', title: 'Uh-Oh' },
  { artist: '(G)I-DLE', title: 'LION' },
  { artist: '(G)I-DLE', title: 'Oh my god' },
  { artist: '(G)I-DLE', title: 'DUMDi DUMDi' },
  { artist: '(G)I-DLE', title: 'HWAA' },
  { artist: '(G)I-DLE', title: 'TOMBOY' },
  { artist: '(G)I-DLE', title: 'Nxde' },
  { artist: '(G)I-DLE', title: 'Queencard' },
  { artist: '(G)I-DLE', title: 'Super Lady' },
  { artist: '(G)I-DLE', title: 'Klaxon' },
  { artist: 'IVE', title: 'ELEVEN' },
  { artist: 'IVE', title: 'LOVE DIVE' },
  { artist: 'IVE', title: 'After LIKE' },
  { artist: 'IVE', title: 'I AM' },
  { artist: 'IVE', title: 'Kitsch' },
  { artist: 'IVE', title: 'Baddie' },
  { artist: 'IVE', title: 'HEYA' },
  { artist: 'NewJeans', title: 'Attention' },
  { artist: 'NewJeans', title: 'Hype Boy' },
  { artist: 'NewJeans', title: 'Cookie' },
  { artist: 'NewJeans', title: 'Ditto' },
  { artist: 'NewJeans', title: 'OMG' },
  { artist: 'NewJeans', title: 'Super Shy' },
  { artist: 'NewJeans', title: 'ETA' },
  { artist: 'NewJeans', title: 'Cool with You' },
  { artist: 'NewJeans', title: 'Get Up' },
  { artist: 'NewJeans', title: 'How Sweet' },
  { artist: 'NewJeans', title: 'Bubble Gum' },
  { artist: 'NewJeans', title: 'Supernatural' },
  { artist: 'LE SSERAFIM', title: 'FEARLESS' },
  { artist: 'LE SSERAFIM', title: 'ANTIFRAGILE' },
  { artist: 'LE SSERAFIM', title: 'UNFORGIVEN' },
  { artist: 'LE SSERAFIM', title: 'Perfect Night' },
  { artist: 'LE SSERAFIM', title: 'EASY' },
  { artist: 'LE SSERAFIM', title: 'CRAZY' },
  { artist: 'LE SSERAFIM', title: 'Smart' },
  { artist: 'STAYC', title: 'SO BAD' },
  { artist: 'STAYC', title: 'ASAP' },
  { artist: 'STAYC', title: 'Stereotype' },
  { artist: 'STAYC', title: 'RUN2U' },
  { artist: 'STAYC', title: 'Teddy Bear' },
  { artist: 'NMIXX', title: 'O.O' },
  { artist: 'NMIXX', title: 'DICE' },
  { artist: 'NMIXX', title: 'Love Me Like This' },
  { artist: 'NMIXX', title: 'DASH' },
  { artist: 'Kep1er', title: 'WA DA DA' },
  { artist: 'Kep1er', title: 'Up!' },
  { artist: 'KISS OF LIFE', title: 'Midas Touch' },
  { artist: 'KISS OF LIFE', title: 'Sticky' },
  { artist: 'BABYMONSTER', title: 'SHEESH' },
  { artist: 'BABYMONSTER', title: 'BATTER UP' },
  { artist: 'BABYMONSTER', title: 'DRIP' },
  { artist: 'ILLIT', title: 'Magnetic' },
  { artist: 'FIFTY FIFTY', title: 'Cupid' },

  // ===== 4th / 5th gen boy groups =====
  { artist: 'Stray Kids', title: "God's Menu" },
  { artist: 'Stray Kids', title: 'Back Door' },
  { artist: 'Stray Kids', title: 'Thunderous' },
  { artist: 'Stray Kids', title: 'MANIAC' },
  { artist: 'Stray Kids', title: 'Case 143' },
  { artist: 'Stray Kids', title: 'S-Class' },
  { artist: 'Stray Kids', title: 'LALALALA' },
  { artist: 'Stray Kids', title: 'MIROH' },
  { artist: 'Stray Kids', title: 'Chk Chk Boom' },
  { artist: 'Stray Kids', title: 'Side Effects' },
  { artist: 'TXT', title: 'Crown' },
  { artist: 'TXT', title: 'Cat & Dog' },
  { artist: 'TXT', title: 'Run Away' },
  { artist: 'TXT', title: "Can't You See Me?" },
  { artist: 'TXT', title: 'Blue Hour' },
  { artist: 'TXT', title: '0X1=LOVESONG' },
  { artist: 'TXT', title: 'LO$ER=LO♡ER' },
  { artist: 'TXT', title: 'Good Boy Gone Bad' },
  { artist: 'TXT', title: 'Sugar Rush Ride' },
  { artist: 'TXT', title: 'Chasing That Feeling' },
  { artist: 'TXT', title: 'Deja Vu' },
  { artist: 'ENHYPEN', title: 'Given-Taken' },
  { artist: 'ENHYPEN', title: 'Drunk-Dazed' },
  { artist: 'ENHYPEN', title: 'Tamed-Dashed' },
  { artist: 'ENHYPEN', title: 'Future Perfect (Pass the MIC)' },
  { artist: 'ENHYPEN', title: 'Bite Me' },
  { artist: 'ENHYPEN', title: 'Sweet Venom' },
  { artist: 'ATEEZ', title: 'Pirate King' },
  { artist: 'ATEEZ', title: 'Say My Name' },
  { artist: 'ATEEZ', title: 'Wonderland' },
  { artist: 'ATEEZ', title: 'Answer' },
  { artist: 'ATEEZ', title: 'Inception' },
  { artist: 'ATEEZ', title: 'Guerrilla' },
  { artist: 'ATEEZ', title: 'Bouncy' },
  { artist: 'ATEEZ', title: 'Crazy Form' },
  { artist: 'ATEEZ', title: 'Halazia' },
  { artist: 'TREASURE', title: 'BOY' },
  { artist: 'TREASURE', title: 'My Treasure' },
  { artist: 'TREASURE', title: 'JIKJIN' },
  { artist: 'TREASURE', title: 'Hello' },
  { artist: 'RIIZE', title: 'Get A Guitar' },
  { artist: 'RIIZE', title: 'Love 119' },
  { artist: 'RIIZE', title: 'Boom Boom Bass' },
  { artist: 'ZEROBASEONE', title: 'In Bloom' },
  { artist: 'ZEROBASEONE', title: 'Crush' },
  { artist: 'ZEROBASEONE', title: 'Feel the POP' },
  { artist: 'P1Harmony', title: 'Do It Like This' },
  { artist: 'BOYNEXTDOOR', title: 'Earth, Wind & Fire' },
  { artist: 'TWS', title: 'Plot Twist' },

  // ===== Soloists =====
  { artist: 'PSY', title: 'Gangnam Style' },
  { artist: 'PSY', title: 'Gentleman' },
  { artist: 'PSY', title: 'Daddy' },
  { artist: 'PSY', title: 'That That' },
  { artist: 'PSY', title: 'New Face' },
  { artist: 'IU', title: 'Good Day' },
  { artist: 'IU', title: 'You & I' },
  { artist: 'IU', title: 'Palette' },
  { artist: 'IU', title: 'BBIBBI' },
  { artist: 'IU', title: 'eight' },
  { artist: 'IU', title: 'Celebrity' },
  { artist: 'IU', title: 'LILAC' },
  { artist: 'IU', title: 'Through the Night' },
  { artist: 'IU', title: 'Blueming' },
  { artist: 'BoA', title: 'No.1' },
  { artist: 'BoA', title: 'Valenti' },
  { artist: 'Rain', title: "It's Raining" },
  { artist: 'Rain', title: 'Rainism' },
  { artist: 'G-Dragon', title: 'Heartbreaker' },
  { artist: 'G-Dragon', title: 'Crooked' },
  { artist: 'G-Dragon', title: 'Crayon' },
  { artist: 'G-Dragon', title: 'POWER' },
  { artist: 'TAEYANG', title: 'Eyes, Nose, Lips' },
  { artist: 'TAEYANG', title: 'Wedding Dress' },
  { artist: 'Taeyeon', title: 'I' },
  { artist: 'Taeyeon', title: 'Why' },
  { artist: 'Taeyeon', title: 'Fine' },
  { artist: 'Taeyeon', title: 'INVU' },
  { artist: 'Taeyeon', title: 'Spark' },
  { artist: 'Sunmi', title: 'Gashina' },
  { artist: 'Sunmi', title: 'Heroine' },
  { artist: 'Sunmi', title: 'Siren' },
  { artist: 'Sunmi', title: 'pporappippam' },
  { artist: 'Sunmi', title: 'TAIL' },
  { artist: 'Chung Ha', title: 'Gotta Go' },
  { artist: 'Chung Ha', title: 'Snapping' },
  { artist: 'Chung Ha', title: 'Bicycle' },
  { artist: 'HyunA', title: 'Bubble Pop!' },
  { artist: 'HyunA', title: 'Red' },
  { artist: 'HyunA', title: 'Ice Cream' },
  { artist: 'Hwa Sa', title: 'Maria' },
  { artist: 'Hwa Sa', title: 'Twit' },
  { artist: 'JENNIE', title: 'SOLO' },
  { artist: 'JENNIE', title: 'You & Me' },
  { artist: 'JENNIE', title: 'Mantra' },
  { artist: 'LISA', title: 'LALISA' },
  { artist: 'LISA', title: 'MONEY' },
  { artist: 'LISA', title: 'Rockstar' },
  { artist: 'ROSÉ', title: 'On The Ground' },
  { artist: 'ROSÉ', title: 'Gone' },
  { artist: 'ROSÉ', title: 'APT.' },
  { artist: 'JISOO', title: 'FLOWER' },
  { artist: 'Jung Kook', title: 'Seven' },
  { artist: 'Jung Kook', title: '3D' },
  { artist: 'Jung Kook', title: 'Standing Next to You' },
  { artist: 'Jimin', title: 'Like Crazy' },
  { artist: 'Jimin', title: 'Who' },
  { artist: 'Agust D', title: 'Daechwita' },
  { artist: 'Agust D', title: 'Haegeum' },
  { artist: 'j-hope', title: 'Chicken Noodle Soup' },
  { artist: 'j-hope', title: 'Arson' },
  { artist: 'BAEKHYUN', title: 'UN Village' },
  { artist: 'BAEKHYUN', title: 'Candy' },
  { artist: 'KAI', title: 'Mmmh' },
  { artist: 'KAI', title: 'Peaches' },
  { artist: 'TAEMIN', title: 'MOVE' },
  { artist: 'TAEMIN', title: 'Criminal' },
  { artist: 'TAEMIN', title: 'Want' },
  { artist: 'ZICO', title: 'Any song' },
  { artist: 'ZICO', title: 'Artist' },
  { artist: 'AKMU', title: '200%' },
  { artist: 'AKMU', title: 'How can I love the heartbreak, you’re the one I love' },
  { artist: 'AKMU', title: 'Love Lee' },
  { artist: 'LeeHi', title: '1, 2, 3, 4' },
  { artist: 'SOMI', title: 'DUMB DUMB' },
  { artist: 'SOMI', title: 'BIRTHDAY' },
  { artist: 'BIBI', title: 'Bam Yang Gang' },
  { artist: 'Crush', title: 'Beautiful' },
  { artist: 'DEAN', title: 'Instagram' },
];

export default CANON;
