INSERT INTO public.groups (name, slug, fandom_name, display_color, text_color) VALUES
  ('BTS',          'bts',          'ARMY',     '#E6F1FB', '#0C447C'),
  ('BLACKPINK',    'blackpink',    'BLINK',    '#FBEAF0', '#72243E'),
  ('Stray Kids',   'stray-kids',   'STAY',     '#EEEDFE', '#3C3489'),
  ('TWICE',        'twice',        'ONCE',     '#FAECE7', '#712B13'),
  ('aespa',        'aespa',        'MY',       '#FAEEDA', '#633806'),
  ('NewJeans',     'newjeans',     'Bunnies',  '#E1F5EE', '#085041'),
  ('SEVENTEEN',    'seventeen',    'CARAT',    '#E6F1FB', '#0C447C'),
  ('EXO',          'exo',          'EXO-L',    '#F1EFE8', '#444441'),
  ('(G)I-DLE',     'g-i-dle',      'Neverland','#EEEDFE', '#3C3489'),
  ('IVE',          'ive',          'DIVE',     '#FBEAF0', '#72243E'),
  ('LE SSERAFIM',  'le-sserafim',  'FEARNOT', '#E1F5EE', '#085041'),
  ('NCT',          'nct',          'NCTzen',   '#EAF3DE', '#27500A'),
  ('Red Velvet',   'red-velvet',   'ReVeluv',  '#FCEBEB', '#791F1F'),
  ('ATEEZ',        'ateez',        'ATINY',    '#FAECE7', '#712B13'),
  ('ENHYPEN',      'enhypen',      'ENGENE',   '#E6F1FB', '#0C447C'),
  ('TXT',          'txt',          'MOA',      '#EEEDFE', '#3C3489'),
  ('ITZY',         'itzy',         'MIDZY',    '#FAEEDA', '#633806'),
  ('NMIXX',        'nmixx',        'NSWer',    '#FBEAF0', '#72243E'),
  ('STAYC',        'stayc',        'SWITH',    '#E1F5EE', '#085041'),
  ('MONSTA X',     'monsta-x',     'Monbebe',  '#F1EFE8', '#444441'),
  ('GOT7',         'got7',         'IGOT7',    '#FAECE7', '#712B13'),
  ('MAMAMOO',      'mamamoo',      'Moomoo',   '#EAF3DE', '#27500A'),
  ('SHINee',       'shinee',       'Shawol',   '#E6F1FB', '#0C447C'),
  ('TREASURE',     'treasure',     'Teume',    '#FAEEDA', '#633806'),
  ('VIVIZ',        'viviz',        'Na.V',     '#FBEAF0', '#72243E'),
  ('Kep1er',       'kep1er',       'Kep1ian',  '#E1F5EE', '#085041'),
  ('BTOB',         'btob',         'Melody',   '#EEEDFE', '#3C3489'),
  ('ASTRO',        'astro',        'AROHA',    '#FAECE7', '#712B13'),
  ('Dreamcatcher', 'dreamcatcher', 'InSomnia', '#FCEBEB', '#791F1F'),
  ('General K-pop','general-kpop', 'fan',      '#F1EFE8', '#444441');
